name: Build foo.exe
description: Build foo.exe
inputs:
  version:
    description: Version to use
    required: false
  platform:
    description: Target platform
    required: true
runs:
  using: composite
  steps:
    - run: |
        $version = '${{ inputs.version }}'
        $version = if ($version) { "-$version" } else { $version }

        $flags = @()
        if ('${{ matrix.platform }}' -eq 'x86') {
            $flags += '-m32'
        }
        $flags += '-std=c++14','-o','foo.exe','foo.cpp'
        if ('${{ runner.os }}' -eq 'Linux') {
            $flags += '-lpthread'
        }

        & "clang++$version" $flags
      shell: pwsh
